# Site settings
title: "I'm Lovin' I.T. - Julien Sobczak"

# Google Analytics
google_analytics: UA-111207061-2


baseurl: "/blog-fr" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Account settings
twitter_username: julien_sobczak

# Build settings
markdown: kramdown
exclude: [ util ]
